const A = window.VYTAL_ASSETS || {};
const COLORS = {black:'#0D0D0D', onyx:'#11100F', carbon:'#1B1917', gold:'#D4AF37', champ:'#F0D58A', bronze:'#8A5A21', ivory:'#F7F4EC', stone:'#D8D2C7', muted:'#9F9A91'};

function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src;});}
function rr(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function wrap(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y);line=word;y+=lineHeight}else line=test}if(line)ctx.fillText(line,x,y);return y}
function bg(ctx){const g=ctx.createRadialGradient(1510,470,60,1510,470,950);g.addColorStop(0,'#211b10');g.addColorStop(.45,'#12110f');g.addColorStop(1,COLORS.black);ctx.fillStyle=g;ctx.fillRect(0,0,1920,1080);ctx.strokeStyle='rgba(212,175,55,.22)';ctx.strokeRect(28,28,1864,1024)}
function logo(ctx,img){ctx.drawImage(img,78,45,210,135)}
function footer(ctx,text='Development concept only • Final design, claims, patent status, and regulatory pathway require professional review, testing, and authorization.'){ctx.strokeStyle=COLORS.bronze;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(72,991);ctx.lineTo(1848,991);ctx.stroke();ctx.font='18px Inter';ctx.fillStyle=COLORS.muted;ctx.fillText(text,72,1030)}
function label(ctx,text,x,y,w){rr(ctx,x,y,w,58,28,COLORS.carbon,COLORS.bronze);ctx.font='600 20px Inter';ctx.fillStyle=COLORS.champ;ctx.textAlign='center';ctx.fillText(text,x+w/2,y+36);ctx.textAlign='left'}
function kicker(ctx,text,x=82,y=255){ctx.font='600 22px Inter';ctx.fillStyle=COLORS.gold;ctx.fillText(text.toUpperCase(),x,y)}
function heading(ctx,text,x=82,y=340,size=74){ctx.font=`500 ${size}px "Cormorant Garamond"`;ctx.fillStyle=COLORS.ivory;ctx.fillText(text,x,y)}
function body(ctx,text,x,y,w=850,size=29){ctx.font=`400 ${size}px Inter`;ctx.fillStyle=COLORS.stone;return wrap(ctx,text,x,y,w,size+13)}
function check(ctx,text,x,y){ctx.strokeStyle=COLORS.gold;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+13,y-8,13,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x+5,y-8);ctx.lineTo(x+11,y-1);ctx.lineTo(x+23,y-18);ctx.stroke();ctx.font='500 27px Inter';ctx.fillStyle=COLORS.ivory;ctx.fillText(text,x+48,y)}
function loadIntoDom(){document.querySelectorAll('[data-vytal-asset]').forEach(el=>{const key=el.dataset.vytalAsset;if(A[key])el.src=A[key]})}

async function renderCard(canvas,type,assets){const ctx=canvas.getContext('2d');bg(ctx);logo(ctx,assets.wordmark);
  if(type==='hero'){
    kicker(ctx,'VYTAL House development platform');heading(ctx,'VYTAL AIR');body(ctx,'A proposed capsule-based dry-powder inhalation platform being prepared for intellectual-property, engineering, physician, and FDA review.',86,445,820,30);ctx.font='500 32px Inter';ctx.fillStyle=COLORS.gold;ctx.fillText('Renew  •  Restore  •  Recharge',90,700);ctx.save();ctx.globalAlpha=.98;ctx.drawImage(assets.product,1190,150,610,760);ctx.restore();label(ctx,'DEVELOPMENT-STAGE • NOT FDA APPROVED',88,820,550);footer(ctx)
  } else if(type==='system'){
    kicker(ctx,'Controlled product architecture');heading(ctx,'THE VYTAL AIR SYSTEM');body(ctx,'One controlled platform. Four coordinated development workstreams.',86,415,1000,28);const ps=[['01','FORMULATION','Composition, stability, aerosol performance, analytical controls.'],['02','DEVICE','Capsule-based DPI interface, airflow, usability, verification.'],['03','PACKAGING','Moisture, oxygen, handling, labeling, and traceability.'],['04','EVIDENCE','Nonclinical, clinical, quality, and regulatory record.']];ps.forEach((p,i)=>{const x=80+i*455;rr(ctx,x,520,415,335,25,'#151412',COLORS.bronze);ctx.font='700 24px Inter';ctx.fillStyle=COLORS.gold;ctx.fillText(p[0],x+28,565);ctx.font='700 31px Inter';ctx.fillStyle=COLORS.ivory;ctx.fillText(p[1],x+28,640);ctx.font='400 23px Inter';ctx.fillStyle=COLORS.stone;wrap(ctx,p[2],x+28,700,350,34)});footer(ctx)
  } else if(type==='physician'){
    kicker(ctx,'Physician review framework');heading(ctx,'ABASI BOMANI, MD');body(ctx,'Clinical and scientific review materials prepared for structured physician evaluation.',86,420,930,28);['Intended-use and benefit–risk questions','Pulmonary safety and tolerability requirements','Formulation, dose, and excipient review','Clinical-development and monitoring framework','Contraindication, interaction, and escalation questions'].forEach((t,i)=>check(ctx,t,92,560+i*70));ctx.save();ctx.beginPath();ctx.arc(1510,500,250,0,Math.PI*2);ctx.clip();ctx.drawImage(assets.doctor,1260,250,500,500);ctx.restore();ctx.strokeStyle=COLORS.gold;ctx.lineWidth=3;ctx.beginPath();ctx.arc(1510,500,252,0,Math.PI*2);ctx.stroke();label(ctx,'REVIEW REQUEST • NO ENDORSEMENT IMPLIED',1220,800,580);footer(ctx,'Development-stage physician-review visual. It does not state that Dr. Bomani has approved the product, protocol, claims, or regulatory pathway.')
  } else if(type==='ip'){
    kicker(ctx,'Intellectual property');heading(ctx,'RIGHTS • DISCLOSURE • PROOF');body(ctx,'A defensible platform starts with accurate inventorship, documented ownership, enabling disclosure, and disciplined filing.',86,440,1160,28);const ss=['INVENTION DISCLOSURE','INVENTORSHIP REVIEW','PATENTABILITY + FTO','PROVISIONAL FILING','NONPROVISIONAL + PCT'];ss.forEach((s,i)=>{const x=90+i*355;ctx.fillStyle='#171512';ctx.strokeStyle=COLORS.gold;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+45,670,45,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='700 28px Inter';ctx.fillStyle=COLORS.champ;ctx.fillText(String(i+1),x+36,680);ctx.font='600 19px Inter';ctx.fillStyle=COLORS.ivory;wrap(ctx,s,x-10,770,220,28);if(i<4){ctx.strokeStyle=COLORS.bronze;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+95,670);ctx.lineTo(x+310,670);ctx.stroke()}});label(ctx,'“PATENT PENDING” ONLY AFTER FILING',90,870,560);footer(ctx)
  } else if(type==='fda'){
    kicker(ctx,'Proposed U.S. regulatory pathway');heading(ctx,'CLASSIFY → ALIGN → TEST → SUBMIT');body(ctx,'Final classification, center assignment, studies, and submission requirements are determined by FDA.',86,435,1150,28);const ss=['CLASSIFICATION','PRE-RFD','PRE-IND','IND','PHASE 1','LATER DEVELOPMENT'];ss.forEach((s,i)=>{const x=70+i*305;rr(ctx,x,555,270,230,24,'#151412',COLORS.bronze);ctx.font='700 22px Inter';ctx.fillStyle=COLORS.gold;ctx.fillText('0'+(i+1),x+25,595);ctx.font='700 25px Inter';ctx.fillStyle=COLORS.ivory;wrap(ctx,s,x+25,680,220,32);if(i<5){ctx.strokeStyle=COLORS.gold;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+270,665);ctx.lineTo(x+305,665);ctx.stroke()}});label(ctx,'PROPOSED PATHWAY • NOT FDA CLEARED OR APPROVED',85,845,720);footer(ctx)
  } else if(type==='capsule'){
    kicker(ctx,'Delivery architecture');heading(ctx,'CAPSULE-BASED DPI CONCEPT');body(ctx,'A passive, reusable dry-powder inhaler with a separately packaged unit-dose capsule—not a vaping device.',86,440,900,29);[['DOSE',1110],['BLISTER',1330],['DEVICE',1550]].forEach(([s,x],i)=>{rr(ctx,x,325,155,445,72,'#191816',COLORS.gold);rr(ctx,x+24,390,107,295,45,'#292824',COLORS.champ);if(i===1){ctx.fillStyle=COLORS.gold;ctx.fillRect(x+27,388,101,78)}ctx.font='600 20px Inter';ctx.fillStyle=COLORS.stone;ctx.textAlign='center';ctx.fillText(s,x+77,820);ctx.textAlign='left'});label(ctx,'NO BATTERY OR CHARGING CLAIM IN THE CONTROLLED CONCEPT',85,820,780);footer(ctx)
  } else if(type==='roadmap'){
    kicker(ctx,'Controlled implementation roadmap');heading(ctx,'FIRST 180 DAYS');const items=[['01','CLEAR','Name, entity, inventorship, ownership'],['02','PROTECT','NDA, assignments, search, provisional'],['03','DEFINE','Product, user needs, requirements'],['04','ALIGN','Pre-RFD and pre-IND questions'],['05','TEST','Formulation, aerosol, device, stability'],['06','DECIDE','Go/no-go, partners, financing']];items.forEach((p,i)=>{const x=55+i*310;rr(ctx,x,480,285,360,24,'#151412',COLORS.bronze);ctx.font='700 22px Inter';ctx.fillStyle=COLORS.gold;ctx.fillText(p[0],x+24,520);ctx.font='700 29px Inter';ctx.fillStyle=COLORS.ivory;ctx.fillText(p[1],x+24,595);ctx.font='400 21px Inter';ctx.fillStyle=COLORS.stone;wrap(ctx,p[2],x+24,665,235,31)});footer(ctx)
  } else if(type==='partner'){
    kicker(ctx,'Development collaboration');heading(ctx,'BUILD THE PLATFORM WITH US');body(ctx,'VYTAL AIR is organizing the expertise required to move responsibly from concept to evidence.',86,430,1120,29);const roles=['Patent & corporate counsel','FDA regulatory strategy','Pulmonary formulation science','Dry-powder inhaler engineering','Inhalation toxicology & clinical development','Quality, manufacturing & data systems'];roles.forEach((r,i)=>{const x=i<3?100:980;const y=535+(i%3)*120;rr(ctx,x,y,780,88,18,'#151412',COLORS.bronze);ctx.font='500 27px Inter';ctx.fillStyle=COLORS.ivory;ctx.fillText(r,x+28,y+55)});label(ctx,'PARTNER INQUIRY • CLINICAL REVIEW • DEVELOPMENT COLLABORATION',560,900,800);footer(ctx)
  }
}

async function init(){loadIntoDom();const [wordmark,product,doctor]=await Promise.all([loadImage(A.wordmark),loadImage(A.product),loadImage(A.doctor)]);const assets={wordmark,product,doctor};await document.fonts.ready;document.querySelectorAll('canvas[data-social-card]').forEach(c=>renderCard(c,c.dataset.socialCard,assets));document.querySelectorAll('[data-download-card]').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.downloadCard;const canvas=[...document.querySelectorAll(`canvas[data-social-card="${type}"]`)][0];if(!canvas)return;const a=document.createElement('a');a.download=`vytal-air-${type}-1920x1080.png`;a.href=canvas.toDataURL('image/png');a.click()}));}

const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('#site-nav');menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));init().catch(console.error);
